### ISSUE TITLE
Follow redirects when getting sitemap and page

### ISSUE THREAD

**Issue by paul90** [WardCunningham/search#4]
I notice that the scape is failing to read the dat sites that being mirrored to https. The dat pinning services do a redirect from `http` to `https`. A possible solution is adding the parameter `-L` to the two curl commands, so that redirects will be followed.

https://github.com/WardCunningham/search/blob/7c64ccb5f8c8baef8e2ebabd2e064c04a761c5e7/scrape.rb#L16

https://github.com/WardCunningham/search/blob/7c64ccb5f8c8baef8e2ebabd2e064c04a761c5e7/scrape.rb#L41

**Comment by WardCunningham** [comment]
s/indirects/redirects/

**Comment by paul90** [comment]
Thanks
